### ISSUE TITLE
Upwork Adil.

### ISSUE THREAD

**Issue by AkioAlex0817** [BunnyNomics101/nftloan#1]
Hi. Peter Tran. I am Adil.
Sorry about the contact using this.
So my Upwork was suspended. 
I am trying to recover the account for 3 days.  But failed.
So I have one ask for you.
Is it possible to continue the project on another channel?
I look forward to continuing the work.
Please contact me. 
My skype is kasumi7007 
Thanks and regards.

**Comment by BunnyNomics101** [comment]
Hi Adil
Thanks for contacting me. Upwork just send me the notice and now my money is stuck!
What's going on? Did you use a fake ID?

Please answer the question with honesty if we want to work together I need to know.

Find me on Discord: 271077#1337

**Comment by AkioAlex0817** [comment]
Thank you very much for your reply.
Sorry about the Upwork issue.
Maybe you can release the stuck money after 7 days.

But, I didn't do anything suspicious. 
I sent a friend request to Discord.
Please check.

**Comment by BunnyNomics101** [comment]
Hi,
You left Discord. 
Can you release the frontend too and we can arrange some kind of payment for your services?

**Comment by BunnyNomics101** [comment]
Hey @AkioAlex0817 
Can you contact me again?

**Comment by BunnyNomics101** [comment]
Hi Adil
Thanks for contacting me. Upwork just send me the notice and now my money
is stuck!
What's going on? Did you use a fake ID?

Please answer the question with honesty if we want to work together I need
to know.

Best regards
Peter


Den tor. 31. mar. 2022 kl. 09.06 skrev AkioAlex ***@***.***>:
